### ISSUE TITLE
如果打开文件夹中获取EXIF信息失败，比如文件夹中包含无法获取的exif信息的mp4，或者其他格式文件会默认重命名为{Date}-{Camera}.mp4

### ISSUE THREAD

**Issue by leowu56** [Arman19941113/rename-photos#1]
是否考虑获取exif文件失败就跳过重命名，而不是使用这种{Date}-{Camera}.mp4进行

**Comment by Arman19941113** [comment]
1. 缺省值加括号不好看，这个暂时不动
2. 对于没有 exif 信息的文件，考虑给表格加个多选框，用户自己决定要不要跳过某些文件
3. 如果想要跳过所有没有 exif 信息的文件，考虑在设置里面加个选项

后面空了搞下

**Comment by Arman19941113** [comment]
> 1. 缺省值加括号不好看，这个暂时不动
> 2. 对于没有 exif 信息的文件，考虑给表格加个多选框，用户自己决定要不要跳过某些文件
> 3. 如果想要跳过所有没有 exif 信息的文件，考虑在设置里面加个选项
> 
> 后面空了搞下

[设置页面新增 EXIF 模式开关，开启后可跳过缺失 EXIF 数据的文件](https://github.com/Arman19941113/rename-photos/releases)
